### ISSUE TITLE
typo3_community_extensions get skipped

### ISSUE THREAD

**Issue by Fjonan** [dachande/typo3-bootstrap#1]
I uncommented some `typo3_community_extensions` in the `configuration.yml` and ran `vagrant provision` but in the console I get this result:

```console
TASK [Prepare installation of TYPO3 community packages] ************************
skipping: [mypage.test] => (item={u'extension_key': u'vhs', u'constraint': None, u'composer_package': u'fluidtypo3/vhs'})
skipping: [mypage.test] => (item={u'extension_key': u'powermail', u'constraint': None, u'composer_package': u'in2code/powermail'})
skipping: [mypage.test] => (item={u'extension_key': u'powermail_cond', u'constraint': None, u'composer_package': u'in2code/powermail_cond'})
skipping: [mypage.test] => (item={u'extension_key': u'femanager', u'constraint': None, u'composer_package': u'in2code/femanager'})
```
After that the packages are not installed. When trying to install the extensions over the `composer_packages` i get the same result.

```console
TASK [Prepare installation of additional composer packages] ********************
skipping: [mypage.test] => (item={u'constraint': None, u'composer_package': u'gridelementsteam/gridelements'})
skipping: [mypage.test] => (item={u'constraint': None, u'composer_package': u'fluidtypo3/vhs'})
skipping: [mypage.test] => (item={u'constraint': None, u'composer_package': u'in2code/powermail'})
skipping: [mypage.test] => (item={u'constraint': None, u'composer_package': u'in2code/powermail_cond'})
skipping: [mypage.test] => (item={u'constraint': None, u'composer_package': u'in2code/femanager'})
```
I also tried to reset everything with `vagrant destroy` and `vagrant up` from scratch, he simply does not install them. I have no idea where I should start to debug this. Installing packages with composer install works fine.

**Comment by dachande** [comment]
Installing extensions set in the configuration file while provisioning the virtual machine should work as long as no composer.json file is present in the project folder.
Otherwise the package requirements set in composer.json take precedence over the packages defined in the configuration file. The settings in the configuration file are only used for the very first time when a new project is initialized.

**Comment by Fjonan** [comment]
Ok works like you described. Could have thought of that :) thanks.
