### ISSUE TITLE
Typo3 10 is released, constraint of typo3_community_extensions must be modified for 9.5

### ISSUE THREAD

**Issue by via-lars** [dachande/typo3-bootstrap#3]
Hi,

from 

`{composer_package: typo3/cms-introduction, extension_key: introduction, constraint: ~}`

to

`{composer_package: typo3/cms-introduction, extension_key: introduction, constraint: 4.0.1}`

in configuration.yml lets the Project install completely now.

**Comment by dachande** [comment]
I have added the needed constraint in release 9.5.4
